services:
  scanner-web:
    build: .
    container_name: scanner-web
    ports:
      - "8088:8080"
    volumes:
      - /share/homes/vandreus/dox:/scans
      - /share/Container/paperless/consume:/paperless
    depends_on:
      - smtp
    restart: unless-stopped
    networks:
      - scanner-net

  smtp:
    image: namshi/smtp
    container_name: scanner-smtp
    restart: unless-stopped
    networks:
      - scanner-net

networks:
  scanner-net:
    driver: bridge
