version: "3.8"
services:
  scanner-web:
    build: .
    container_name: scanner-web
    restart: unless-stopped
    ports:
      - "8088:8080"
    volumes:
      - /share/Dox/Scan:/scans
      - /share/Container/paperless/consume:/paperless
    networks:
      - scanner-net

networks:
  scanner-net:
    driver: bridge
